#!/bin/bash
#NOM    : Demo
#CLASSE : ED - LaboED 03-01
#OBJET  : réservé au makefile
#AUTEUR	: J.C. Jaumain, 07/2011
clear
C='\033[44m'
E='\033[32m\033[1m'
W='\033[31m\033[1m'
N='\033[0m'
echo "Démonstration du programme ContenuRepertoire"
echo "--------------------------------------------"
echo
echo -e "Éxecution de ${E}./ContenuRepertoire${N} :"
echo
./ContenuRepertoire
echo
echo "Vérification"
echo "------------"
echo "Par comparaison, un ls donne :"
echo
ls -ai | cat		# cat pour forcer un fichier par ligne
echo -e "${C}             --> Enter pour continuer${N}"
read
